project_id = "pqdjfjenbdtpkrwqpptj"

[functions.send-contact-email]
verify_jwt = false

[functions.send-solicitud-convocatoria]
verify_jwt = false

[functions.send-solicitud-voluntario]
verify_jwt = false

[functions.send-inscripcion-ruta-dorada]
verify_jwt = false

[functions.send-programa-inscripcion]
verify_jwt = false
